user_name= input("What's your name?: ")  

user_surname= input("What's your surname?: ")

user_age= input("What's your age?: ") 

user_datebirth= input("Put your date birth: ") 

siblings= input("Do you have siblings?: ") 

Password= input("Create Password: ") 

Confirm_Password= input("Confirm Password: ") 


print("What's your name?: " + user_name + "/" "What's your surname?: " + user_surname + "/" "What's your age?: " + user_age + "/" "Put your date birth: " + user_datebirth + "/" "Do you have siblings?: " + siblings + "/" "Create password" + Password + "/" "Confirm password"  + Confirm_Password)